return {
  "catppuccin/nvim",
  name = "catppuccin",
  opts = {
    dim_inactive = { enabled = true, percentage = 0.25 },
    integration_default = false,
    integrations = {
      aerial = true,
      cmp = true,
      dap = { enabled = true, enable_ui = true },
      gitsigns = true,
      headlines = true,
      markdown = true,
      mason = true,
      native_lsp = { enabled = true, inlay_hints = { background = false } },
      neogit = true,
      neotree = true,
      noice = true,
      notify = true,
      rainbow_delimiters = true,
      sandwich = true,
      semantic_tokens = true,
      symbols_outline = true,
      telescope = { enabled = true, style = "nvchad" },
      treesitter = true,
      which_key = true,
    },
    custom_highlights = {
      -- disable italics  for treesitter highlights
      TabLineFill = { link = "StatusLine" },
      LspInlayHint = { style = { "italic" } },
      ["@parameter"] = { style = {} },
      ["@type.builtin"] = { style = {} },
      ["@namespace"] = { style = {} },
      ["@text.uri"] = { style = { "underline" } },
      ["@tag.attribute"] = { style = {} },
      ["@tag.attribute.tsx"] = { style = {} },
    },
  },
}
